# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dccba14e628e0a23a9197e83dd0629429448ff3b588d39282c7c2bb9de50a00f8e8335145cb01ccf4eb913faec5da7dacdaeac748339d8de7dc41445665fb335

test:
  secret_key_base: 56668710424a7bc799b965d79ac0ee917b7abbf466197910b4a9ad463246fe000b32a6f8e63a1de98f71aca1b85e93fcb588913888a82be0fc7f0386ab3f8c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
